# Site settings
title: Thrill
email: thrill@panthema.net
description: > # this means to ignore newlines until "baseurl:"
  Thrill is a C++ framework for distributed Big Data computations on a cluster.
  It is currently in development and aims to be more versatile and performant
  than Java-based alternatives.
baseurl: ""
url: "http://thrill.github.io"
source_link: "https://github.com/PdF14-MR/c7a"
github_username: thrill
favicon:     "assets/favicon.ico"
touch_icon:  "assets/apple-touch-icon.png"
google_analytics_key: UA-66409178-1 ## blank to disable

# Build settings
markdown: kramdown

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
port: 4000
host: 0.0.0.0
safe: false
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
